version: '3'

services:
  postgresql:
    image: postgres
    container_name: squadhelp
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DATABASE=squadhelp
    command: postgres
    restart: always