version: '3.9'

services:
  server-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db-dev
    env_file:
      - .env
    volumes:
      - ../public:/public
      - .:/server
      - /server/node_modules

  db-dev:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT_POSTGRES}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  server-dev:
  postgres_data:
