version: '3'

services:
  postgresql:
    image: postgres
    container_name: squadhelp
    env_file: .env
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_NAME}
    command: postgres
    restart: always