import { Offer, OfferStatus } from '@prisma/client';

export const offersMockDataFirstCreator: Partial<Offer>[] = [
	{
		userId: null,
		contestId: null,
		text: 'first',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'second',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'third',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'fourth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'fifth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'sixth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'seventh',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'eighth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'ninth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'tenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'eleventh',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'twelfth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'thirteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'fourteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'seventeenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'eighteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
];

export const offersMockDataSecondCreator: Partial<Offer>[] = [
	{
		userId: null,
		contestId: null,
		text: 'fifteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'sixteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'nineteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
];
