import { CreateUserDto, UpdateUserDto } from '../../src/common/dto/user';
import {
	BrandStyle,
	Contest,
	ContestStatus,
	ContestType,
	Industry,
	Offer,
	OfferStatus,
	Role,
	StyleName,
	TypeOfName,
	TypeOfTagline,
} from '@prisma/client';
import {
	LogoContestUpdateDto,
	NameContestUpdateData,
	QueryCreatorContestDto,
	QueryCustomerContestDto,
	QueryModeratorContestDto,
	TagLineContestUpdateDto,
} from '../../src/common/dto/contest';
import { Decimal } from '@prisma/client/runtime/library';

export const userMockDataFirstCustomer: CreateUserDto = {
	firstName: 'Ragnar',
	lastName: 'Lodbrok',
	displayName: 'ragnarek',
	email: 'ragnartest@gmail.com',
	password: 'Ragnar123+',
	role: Role.customer,
};

export const userMockDataSecondCustomer: CreateUserDto = {
	firstName: 'Dean',
	lastName: 'Winchester',
	displayName: 'dean',
	email: 'supernaturaltest@gmail.com',
	password: 'Winchester123+',
	role: Role.customer,
};

export const userMockDataFirstCreator: CreateUserDto = {
	firstName: 'Geralt',
	lastName: 'Witcher',
	displayName: 'witcher',
	email: 'witchertest@gmail.com',
	password: 'Geralt123+',
	role: Role.creator,
};

export const userMockDataSecondCreator: CreateUserDto = {
	firstName: 'Sam',
	lastName: 'Winchester',
	displayName: 'sam',
	email: 'sam_supernaturaltest@gmail.com',
	password: 'Sam_winchester123+',
	role: Role.creator,
};

export const userUpdateMockData: UpdateUserDto = {
	firstName: 'RagnarUp',
	lastName: 'LodbrokUp',
	displayName: 'ragnarekUp',
	avatar: 'anon.png',
	deleteFileName: '',
};

export const contestMockDataFirstCustomer: Partial<Contest>[] = [
	{
		contestType: ContestType.name,
		fileName: null,
		originalFileName: null,
		title: 'First',
		typeOfName: TypeOfName.Company,
		industry: Industry.CreativeAgency,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: StyleName.Classic,
		nameVenture: null,
		typeOfTagline: null,
		status: ContestStatus.active,
		brandStyle: null,
		price: new Decimal(100),
		priority: 1,
		orderId: '0099108a-080d-42e4-8c0a-a693d0c0e2c0',
		userId: null,
	},
	{
		contestType: ContestType.name,
		fileName: null,
		originalFileName: null,
		title: 'Third',
		typeOfName: TypeOfName.Company,
		industry: Industry.CreativeAgency,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: StyleName.Classic,
		nameVenture: null,
		typeOfTagline: null,
		status: ContestStatus.active,
		brandStyle: null,
		price: new Decimal(100),
		priority: 1,
		orderId: 'd4026df1-78c2-46f5-9432-b32275ff5cbb',
		userId: null,
	},
	{
		contestType: ContestType.name,
		fileName: null,
		originalFileName: null,
		title: 'fifth',
		typeOfName: TypeOfName.Company,
		industry: Industry.CreativeAgency,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: StyleName.Classic,
		nameVenture: null,
		typeOfTagline: null,
		status: ContestStatus.active,
		brandStyle: null,
		price: new Decimal(100),
		priority: 1,
		orderId: '6f6a173c-b998-4e35-be85-054b6a995279',
		userId: null,
	},
	{
		contestType: ContestType.name,
		fileName: null,
		originalFileName: null,
		title: 'seventh',
		typeOfName: TypeOfName.Product,
		industry: Industry.ConsultingFirm,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: StyleName.Classic,
		nameVenture: null,
		typeOfTagline: null,
		status: ContestStatus.finished,
		brandStyle: null,
		price: new Decimal(100),
		priority: 1,
		orderId: 'a96e7f14-65cf-44ad-a9ad-546837e80790',
		userId: null,
	},
	{
		contestType: ContestType.tagline,
		fileName: null,
		originalFileName: null,
		title: 'ninth',
		typeOfName: null,
		industry: Industry.CreativeAgency,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: null,
		nameVenture: 'name venture',
		typeOfTagline: StyleName.Classic,
		status: ContestStatus.active,
		brandStyle: null,
		price: new Decimal(100),
		priority: 1,
		orderId: '2b5d8aa9-1a5c-407c-b9b6-aa366cedd23a',
		userId: null,
	},
];

export const contestMockDataSecondCustomer: Partial<Contest>[] = [
	{
		contestType: ContestType.name,
		fileName: null,
		originalFileName: null,
		title: 'Second',
		typeOfName: TypeOfName.Product,
		industry: Industry.ConsultingFirm,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: StyleName.Classic,
		nameVenture: null,
		typeOfTagline: null,
		status: ContestStatus.active,
		brandStyle: null,
		price: new Decimal(100),
		priority: 1,
		orderId: '3a8ec870-57ea-415f-9e7e-8258e3ef7b46',
		userId: null,
	},
	{
		contestType: ContestType.name,
		fileName: null,
		originalFileName: null,
		title: 'Fourth',
		typeOfName: TypeOfName.Company,
		industry: Industry.CreativeAgency,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: StyleName.Classic,
		nameVenture: null,
		typeOfTagline: null,
		status: ContestStatus.active,
		brandStyle: null,
		price: new Decimal(100),
		priority: 1,
		orderId: '124f0c9b-d510-4eb4-afa2-fb9f8e38349f',
		userId: null,
	},
	{
		contestType: ContestType.name,
		fileName: null,
		originalFileName: null,
		title: 'Sixth',
		typeOfName: TypeOfName.Company,
		industry: Industry.Education,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: StyleName.Classic,
		nameVenture: null,
		typeOfTagline: null,
		status: ContestStatus.active,
		brandStyle: null,
		price: new Decimal(100),
		priority: 1,
		orderId: '5049c3e4-e575-4547-b516-d6db413527c4',
		userId: null,
	},
	{
		contestType: ContestType.tagline,
		fileName: null,
		originalFileName: null,
		title: 'Eighth',
		typeOfName: null,
		industry: Industry.CreativeAgency,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: null,
		nameVenture: 'name venture',
		typeOfTagline: TypeOfTagline.Classic,
		status: ContestStatus.pending,
		brandStyle: null,
		price: new Decimal(100),
		priority: 2,
		orderId: '5049c3e4-e575-4547-b516-d6db413527c4',
		userId: null,
	},
	{
		contestType: ContestType.logo,
		fileName: null,
		originalFileName: null,
		title: 'Tenth',
		typeOfName: null,
		industry: Industry.CreativeAgency,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: null,
		nameVenture: 'name venture',
		typeOfTagline: null,
		status: ContestStatus.pending,
		brandStyle: BrandStyle.Tech,
		price: new Decimal(100),
		priority: 3,
		orderId: '5049c3e4-e575-4547-b516-d6db413527c4',
		userId: null,
	},
	{
		contestType: ContestType.logo,
		fileName: null,
		originalFileName: null,
		title: 'eleventh',
		typeOfName: null,
		industry: Industry.CreativeAgency,
		focusOfWork: 'What does your company',
		targetCustomer: 'Tell us about your customers',
		styleName: null,
		nameVenture: 'name venture',
		typeOfTagline: null,
		status: ContestStatus.active,
		brandStyle: BrandStyle.Tech,
		price: new Decimal(100),
		priority: 1,
		orderId: '5cfeb361-4d68-40a0-9c7b-077995e250fc',
		userId: null,
	},
];

export const offersMockDataFirstCreator: Partial<Offer>[] = [
	{
		userId: null,
		contestId: null,
		text: 'first',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'second',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'third',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'fourth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'fifth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'sixth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'seventh',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'eighth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'ninth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'tenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'eleventh',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'twelfth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'thirteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'fourteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'seventeenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
	{
		userId: null,
		contestId: null,
		text: 'eighteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
];

export const offersMockDataSecondCreator: Partial<Offer>[] = [
	{
		userId: null,
		contestId: null,
		text: 'fifteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'sixteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.active,
	},
	{
		userId: null,
		contestId: null,
		text: 'nineteenth',
		fileName: null,
		originalFileName: null,
		status: OfferStatus.pending,
	},
];

export const queryGetContestsCustomerAll: QueryCustomerContestDto = {
	limit: 8,
	page: 0,
	status: 'all' as ContestStatus,
};

export const queryGetContestsCustomerActive: QueryCustomerContestDto = {
	limit: 8,
	page: 0,
	status: 'active',
};

export const queryGetContestsCreatorAll: QueryCreatorContestDto = {
	limit: 8,
	page: 0,
	status: 'all' as ContestStatus,
	industry: 'all' as Industry,
	typeIndex: 'name,tagline,logo',
	contestId: null,
	awardSort: 'asc',
	ownEntries: 'false',
};

export const queryGetContestsCreatorActive: QueryCreatorContestDto = {
	limit: 8,
	page: 0,
	status: ContestStatus.active,
	industry: Industry.ConsultingFirm,
	typeIndex: 'name',
	contestId: null,
	awardSort: 'asc',
	ownEntries: 'false',
};

export const queryGetContestsModeratorAll: QueryModeratorContestDto = {
	limit: 8,
	page: 0,
	industry: 'all' as Industry,
	typeIndex: 'name,tagline,logo',
	contestId: null,
};

export const updateContestTypeName: NameContestUpdateData = {
	title: 'UpdateContestName',
	typeOfName: TypeOfName.Project,
	focusOfWork: 'update focus of work',
	industry: Industry.Medical,
	styleName: StyleName.Youthful,
	targetCustomer: 'update target customer',
};

export const updateContestTypeTagLine: TagLineContestUpdateDto = {
	title: 'UpdateContestTagLine',
	focusOfWork: 'update focus of work',
	industry: Industry.Education,
	targetCustomer: 'update target customer',
	typeOfTagline: TypeOfTagline.Modern,
	nameVenture: 'update name venture',
};

export const updateContestTypeLogo: LogoContestUpdateDto = {
	title: 'UpdateContestLogo',
	focusOfWork: 'update focus of work',
	industry: Industry.Education,
	targetCustomer: 'update target customer',
	brandStyle: BrandStyle.Minimal,
	nameVenture: 'update name venture',
};
